name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select the Terraform action"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    name: "Terraform ${{ github.event.inputs.action }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    env:
      ACCESS_KEY: ${{ secrets.CA_ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.CA_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Configure Terraform CLI
        run: |
          cat > ~/.terraformrc << EOF
          provider_installation {
            network_mirror {
              url = "https://terraform-mirror.yandexcloud.net/"
              include = ["registry.terraform.io/*/*"]
            }
            direct {
              exclude = ["registry.terraform.io/*/*"]
            }
          }
          EOF

      - name: Remove existing lock file
        run: rm -f .terraform.lock.hcl

      - name: Create environment file
        run: |
          cat > terraform.tfvars << EOF
          zone           = "${{secrets.TF_ZONE }}"
          folder_id      = "${{secrets.TF_FOLDER_ID }}"
          catalog_name   = "${{secrets.TF_CATALOG_NAME }}""
          image_id       = "${{secrets.TF_IMAGE_ID }}"
          ssh_public_key = "${{secrets.PUBLIC_SSH_KEY }}"
          vm_user        = "${{secrets.TF_VM_USER }}"
          EOF

      - name: Terraform init
        run: terraform init -backend-config="access_key=$ACCESS_KEY" -backend-config="secret_key=$SECRET_KEY"

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: terraform plan

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve
